config/routes.rb
Rails.application.routes.draw do
  resources :collab_requests
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end
  resources :comments, except: [:index, :show]
  resources :items, except: [:index]
  resources :lists, except: [:index]
  resources :collaborations

  get 'static_pages/home'
  get :search, controller: :static_pages
  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items
  has_many :comments
  has_many :collaborations, class_name: "Collaboration", foreign_key: "collab_id"
  has_many :collaborators, class_name: 'User', through: :collaborations
  has_many :collab_requests
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @comments = @list.comments
    @comment = Comment.new
    @items = @list.items
    @collaborators = @list.collaborators
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :owner_can_participate)
    end
end

app/helpers/lists_helper.rb
module ListsHelper

  def list_belongs_to_user?(list)
    user_signed_in? && list.user_id == current_user.id
  end

  def user_can_participate?(list)
    (user_signed_in? && list.user_id != current_user.id && Collaboration.exists?(collab: list, collaborator: current_user.id)) ||
    (list_belongs_to_user?(list) && list.owner_can_participate?)
  end

  def show_request_button?(list)
    user_signed_in? &&
    !list_belongs_to_user?(list) &&
    !Collaboration.exists?(collab: list, collaborator: current_user.id) &&
    !CollabRequest.exists?(user: current_user, list: list)
  end

  def show_request_sent?(list)
    CollabRequest.exists?(user: current_user, list: list)
  end

end

app/views/lists/_form.html.erb
<%= form_with(model: list, local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :owner_can_participate %>
    <%= form.check_box :owner_can_participate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', profile_path(current_user.id) %>

app/views/lists/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h3><%= @list.name %> <small>by: <%= @list.user.username %></small></h3>

    <% if list_belongs_to_user?(@list)%>
      <%= link_to 'Edit List Properties', edit_list_path(@list) %>
    <% end %>
    <br />
    <% if list_belongs_to_user?(@list) || user_can_participate?(@list)%>
      <%= link_to 'New Item', new_item_path(list_id: @list.id)%>
      <br/>
      <br/>
    <% end %>
    <div class="table-responsive">
      <table class="table">
      <% @items.each do |item| %>
        <tr>
          <td class="w-auto"><%= item.name  %></td>
          <td><%= link_to 'Buy Here', item.url %></td>
          <td><%= item.instructions %></td>

          <% if list_belongs_to_user?(@list) || user_can_participate?(@list) %>
            <td><%= link_to 'edit', edit_item_path(item) %></td>
            <td><%= link_to 'delete', item, method: :delete %></td>
          <% end %>

          <% if user_can_participate?(@list) && !item.purchaser %>
            <td><%= button_to 'Mark as Purchased', item_path(item: {purchaser_id: current_user.id}, item_id: item.id), method: :put %></td>
          <% elsif user_can_participate?(@list) && item.purchased? %>
            <td> purchased by: <%= item.purchaser.username %></td>
          <% end %>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
  <div class="col-md-3">
    <h5>Collaborators</h5>
    <% if list_belongs_to_user?(@list) %>
      <%= form_with url: search_path, local: true, method: :get do |form| %>
        <%= form.text_field :q, placeholder: "Invite", data: {behavior: "autocomplete"} %>
        <%= form.submit "Search", class: "btn btn-outline-success" %>
        <%= form.hidden_field :list_id, :value => @list.id %>
      <% end %>
    <% elsif show_request_button?(@list)%>
      <%= button_to 'request to join', collab_requests_path(collab_request: {user_id: current_user.id, list_id: @list.id, from_owner: false}) %>
    <% elsif show_request_sent?(@list) %>
      request pending approval.
    <% end %>
    <% @collaborators.each do |collab| %>
      <div>
        <%= link_to collab.username, profile_path(collab.id) %>
      </div>
    <% end %>
  </div>
</div>

<% if user_can_participate?(@list)%>
  <h3>Comments</h3>
  <%= render 'comments/form', comment: @comment, list_id: @list.id %>

  <%= render partial: 'comments/comment', collection: @comments %>
<% end %>