config/routes.rb
Rails.application.routes.draw do
  resources :collab_requests
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end
  resources :comments, except: [:index, :show]
  resources :items, except: [:index]
  resources :lists, except: [:index]
  resources :collaborations

  get 'static_pages/home'
  get :search, controller: :static_pages
  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @lists = []
    @collabs = []
    if user_signed_in?
      @lists = current_user.lists
      @collabs = current_user.collabs
    else
      redirect_to new_user_session_path
    end
  end

  def search
    filtered_users = User.joins(:collaborations).where(collaborations: {collab_id: params[:list_id]})
    filtered_users += User.where(id: current_user.id)
    @list = List.find(params[:list_id])

    @users = User.ransack(username_cont: params[:q])
            .result(distinct: true)
            .where.not(id: filtered_users)

    respond_to do |format|
      format.html {}
      format.json{
        @users = @users.limit(5)
      }
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
  <h3>Your Lists</h3>
  <%= link_to "Create a new list", new_list_path %>
  <br/>
  <br/>
  <% @lists.each do |list| %>
    <div>
      <p><%= link_to list.name, list_path(list) %></p>
    </div>
  <% end %>
  <h3>Your Collabs</h3>
  <% @collabs.each do |list| %>
    <div>
      <p><%= link_to list.name, list_path(list) %></p>
    </div>
  <% end %>
<% end %>

app/views/static_pages/search.html.erb
<h5>Results for Search: </h5>
<table class="table">
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, profile_path(user.id) %></td>
      <td><%= link_to 'Invite', collab_requests_path(collab_request: {user_id: user.id, list_id: @list.id, from_owner: true}), method: :post %> </td>
    </tr>
  <% end %>
</table>