config/routes.rb
Rails.application.routes.draw do
  resources :collab_requests
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'profile'
  end
  resources :comments, except: [:index, :show]
  resources :items, except: [:index]
  resources :lists, except: [:index]
  resources :collaborations

  get 'static_pages/home'
  get :search, controller: :static_pages
  root to: "static_pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collab_request.rb
class CollabRequest < ApplicationRecord
  belongs_to :user
  belongs_to :list
  validates_uniqueness_of :user_id, scope: :list_id
end

app/controllers/collab_requests_controller.rb
class CollabRequestsController < ApplicationController
  before_action :set_collab_request, only: [:show, :edit, :update, :destroy]

  # GET /collab_requests
  # GET /collab_requests.json
  def index
    @collab_requests = CollabRequest.joins(:list).where(lists: {user_id: current_user.id}, from_owner: false)
    @collab_invites = current_user.collab_requests
  end

  # GET /collab_requests/1
  # GET /collab_requests/1.json
  def show
  end

  # GET /collab_requests/new
  def new
    @collab_request = CollabRequest.new
  end

  # GET /collab_requests/1/edit
  def edit
  end

  # POST /collab_requests
  # POST /collab_requests.json
  def create
    @collab_request = CollabRequest.new(collab_request_params)

    respond_to do |format|
      if @collab_request.save
        format.html { redirect_to list_path(@collab_request.list_id), notice: 'Collab request was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @collab_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collab_requests/1
  # PATCH/PUT /collab_requests/1.json
  def update
    respond_to do |format|
      if @collab_request.update(collab_request_params)
        format.html { redirect_to @collab_request, notice: 'Collab request was successfully updated.' }
        format.json { render :show, status: :ok, location: @collab_request }
      else
        format.html { render :edit }
        format.json { render json: @collab_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collab_requests/1
  # DELETE /collab_requests/1.json
  def destroy
    @collab_request.destroy
    respond_to do |format|
      format.html { redirect_to collab_requests_url, notice: 'Collab request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collab_request
      @collab_request = CollabRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collab_request_params
      puts "params here: " + params.inspect
      params.require(:collab_request).permit(:user_id, :list_id, :from_owner)
    end
end

app/helpers/collab_requests_helper.rb
module CollabRequestsHelper
end

app/views/collab_requests/_form.html.erb
<%= form_with(model: collab_request, local: true) do |form| %>
  <% if collab_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collab_request.errors.count, "error") %> prohibited this collab_request from being saved:</h2>

      <ul>
      <% collab_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collab_requests/edit.html.erb
<h1>Editing Collab Request</h1>

<%= render 'form', collab_request: @collab_request %>

<%= link_to 'Show', @collab_request %> |
<%= link_to 'Back', collab_requests_path %>

app/views/collab_requests/index.html.erb
<h3>Collaboration Requests</h3>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @collab_requests.each do |collab_request| %>
      <tr>
        <td><%= link_to collab_request.user.username, profile_path(collab_request.user.id) %></td>
        <td>List: <%= link_to collab_request.list.name, list_path(collab_request.list.id) %></td>
        <td><%= link_to 'Accept', collaborations_path(collab_request: collab_request), method: :post %></td>
        <td><%= link_to 'Deny', collab_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Collaboration Invites</h3>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @collab_invites.each do |collab_invite| %>
      <tr>
        <td><%= link_to collab_invite.list.user.username, profile_path(collab_invite.list.user.id) %></td>
        <td>List: <%= link_to collab_invite.list.name, list_path(collab_invite.list.id) %></td>
        <td><%= link_to 'Accept', collaborations_path(collab_request: collab_invite), method: :post %></td>
        <td><%= link_to 'Deny', collab_invite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/collab_requests/new.html.erb
<h1>New Collab Request</h1>

<%= render 'form', collab_request: @collab_request %>

<%= link_to 'Back', collab_requests_path %>

app/views/collab_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_collab_request_path(@collab_request) %> |
<%= link_to 'Back', collab_requests_path %>